### PR TITLE
10 request to add check for cscvw33061

### PR DESCRIPTION
**Pull request by wilsonbc2**
Fix for issue #10 . Tested via test_logic and lab APIC.

### CODE REVIEW

**Comment by monrog2** [comment]
Last request, change output to:
1. remove target version (user has to manually select this in the beginning and its displayed up top)
2. Add the specific VLAN block(s) that are set to internal

Example:
```
[Check 40/40] Internal VLAN Pool Check...                                                                          FAIL - OUTAGE WARNING!!
  VLAN Pool        VLAN Block                          Warning
  ---------        -------                             -------
  jr-dynamic-pool  from-[vlan-3100]-to-[vlan-3200]     Encap block has role "internal" and is associated to a non-AVE domain

  Recommended Action: Ensure any VLAN Encap blocks explicitly used for leaf front panel VLAN programming are set to "external (on the wire)"
  Reference Document: https://bst.cloudapps.cisco.com/bugsearch/bug/CSCvw33061

**Comment by wilsonbc2** [comment]
Internal VLAN Blocks and Non-AVE Domains are now displayed in data section. Tested all scenarios.

```
Test #1: Physical domain associated to internal vlan pool

[Check 40/40] Internal VLAN Pool Check...                                                                          FAIL - OUTAGE WARNING!!
  VLAN Pool  Internal VLAN Block(s)                                          Non-AVE Domain         Warning
  ---------  ----------------------                                          --------------         -------
  bw-ave     from-[vlan-100]-to-[vlan-100], from-[vlan-1100]-to-[vlan-1199]  uni/phys-bw-physical2  VLAN Pool contains an encap block with role "internal" and is associated to a non-AVE domain
  
  
Test #2: DVS domain associated to internal vlan pool

[Check 40/40] Internal VLAN Pool Check...                                                                          FAIL - OUTAGE WARNING!!
  VLAN Pool  Internal VLAN Block(s)                                          Non-AVE Domain                   Warning
  ---------  ----------------------                                          --------------                   -------
  bw-ave     from-[vlan-100]-to-[vlan-100], from-[vlan-1100]-to-[vlan-1199]  uni/vmmp-VMware/dom-bw-dvs-test  VLAN Pool contains an encap block with role "internal" and is associated to a non-AVE domain

Test #3: Multiple non-AVE domains associated to multiple internal vlan pools

[Check 40/40] Internal VLAN Pool Check...                                                                          FAIL - OUTAGE WARNING!!
  VLAN Pool     Internal VLAN Block(s)                                          Non-AVE Domain                   Warning
  ---------     ----------------------                                          --------------                   -------
  bw-ave        from-[vlan-100]-to-[vlan-100], from-[vlan-1100]-to-[vlan-1199]  uni/vmmp-VMware/dom-bw-dvs-test  VLAN Pool contains an encap block with role "internal" and is associated to a non-AVE domain
  bw-phys-test  from-[vlan-400]-to-[vlan-500]                                   uni/phys-bw-physical2            VLAN Pool contains an encap block with role "internal" and is associated to a non-AVE domain
  bw-phys-test  from-[vlan-400]-to-[vlan-500]                                   uni/phys-bw-physical3            VLAN Pool contains an encap block with role "internal" and is associated to a non-AVE domain

Test #4: AVE Domain associated to internal vlan pool

[Check 40/40] Internal VLAN Pool Check...                                                                                             PASS

Test #5: Target version less than 4.2(6)

You have chosen version "aci-apic-dk9.4.1.2g.bin"
...
[Check 40/40] Internal VLAN Pool Check...                                                                                             PASS


Test #6: No target version selected

No Firmware Detected!  Please Upload APIC Firmware and re-run the script.
...
[Check 40/40] Internal VLAN Pool Check... Target version not supplied. Skipping.                                     MANUAL CHECK REQUIRED

**Comment by monrog2** [comment]
latest pytest positive result, going to merge:
```
[Check  4/7] Internal VLAN Pool Check...                                                                          FAIL - OUTAGE WARNING!!
  VLAN Pool        Internal VLAN Block(s)           Non-AVE Domain              Warning
  ---------        ----------------------           --------------              -------
  jr-dynamic-pool  from-[vlan-3100]-to-[vlan-3200]  uni/vmmp-VMware/dom-jr-dvs  VLANs in this Block will be removed from switch Front-Panel if not corrected

  Recommended Action: Ensure Leaf Front-Panel VLAN Blocks are explicitly set to "external (on the wire)"
  Reference Document: https://bst.cloudapps.cisco.com/bugsearch/bug/CSCvw33061
```

**Review by monrog2 — APPROVED** [review]
merging

**Pull request merged**
